// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeuNlqLEFTSo2UsRgYSn6MtKuVBie49f8',
    appId: '1:129755676637:web:47f640d3703261d2940034',
    messagingSenderId: '129755676637',
    projectId: 'app-de-cadastro-imobiliario',
    authDomain: 'app-de-cadastro-imobiliario.firebaseapp.com',
    storageBucket: 'app-de-cadastro-imobiliario.appspot.com',
    measurementId: 'G-G56DXXTFMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRQpfnlr8Y06KZ_-teC6pSVE6ORW4KynQ',
    appId: '1:129755676637:android:57c76d8c1985f624940034',
    messagingSenderId: '129755676637',
    projectId: 'app-de-cadastro-imobiliario',
    storageBucket: 'app-de-cadastro-imobiliario.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWZUee40r016HhbybETm59ZIwG3yMnou8',
    appId: '1:129755676637:ios:84c6545cccd5eec9940034',
    messagingSenderId: '129755676637',
    projectId: 'app-de-cadastro-imobiliario',
    storageBucket: 'app-de-cadastro-imobiliario.appspot.com',
    iosClientId: '129755676637-34egkihli0190gd8j5isscv2rvdavfqq.apps.googleusercontent.com',
    iosBundleId: 'br.com.florarosa.projetoPrefeitura',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWZUee40r016HhbybETm59ZIwG3yMnou8',
    appId: '1:129755676637:ios:84c6545cccd5eec9940034',
    messagingSenderId: '129755676637',
    projectId: 'app-de-cadastro-imobiliario',
    storageBucket: 'app-de-cadastro-imobiliario.appspot.com',
    iosClientId: '129755676637-34egkihli0190gd8j5isscv2rvdavfqq.apps.googleusercontent.com',
    iosBundleId: 'br.com.florarosa.projetoPrefeitura',
  );
}
